### ISSUE TITLE
AWS WAF is blocking http request

### ISSUE THREAD

**Issue by shossain-mizzou** [Missouri-BMI/I2B2_SERVERLESS#18]
AWS WAF (CreatedByALB-f5669c7ac97a68a4) in App-Web-Dev is blocking following resource :
https://shrine-dev.nextgenbmi.umsystem.edu/Shibboleth.sso/SAML2/POST

due to,
AWS#AWSManagedRulesCommonRuleSet#SizeRestrictions_BODY

Typically SAML POST method sends encryped messages which are larger in size. We had similar adjustment in the i2b2 WAF.

Would you clone following rules from i2b2 WAF to both shrine ALB assoicated WAF?
- BodySizeConstraint
- Allow_shibbolethsso

**Comment by aaronmbruce** [comment]
I have created the allow_shibbolethsso and BodySizeConstraint rules in CreatedByALB-f5669c7ac97a68a4
